Parameter: 
    BucketName:
        Type: String
        Description: Name of the S3 bucket to create

Resource: 
  LambdaBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName
    