Parameters: 
    BucketName:
        Type: String
        Description: Name of the S3 bucket to create

Resources: 
  LambdaBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName

Outputs:
    BucketName:
        Value: !Ref LambdaBucket
        Description: Name of the S3 bucket created
        Export:
            Name: !Sub "RedditWipeBucket"